person:
  name: 張三
  age: 188
  #birthday: 2010/10/10 12:12:12
  birthday: 2023-06-14T10:15:30
  like: true
  child:
    name: 李四
    age: 10
#    birthday: 2018/11/11
    birthday: 2023-06-14
    text: ["abc", "def"]
  dogs:
    - name: 小黑
    - age: 3
    - name: 小白
    - age: 2
  cats:
    c1:
      name: 小蘭
      age: 3
    c2: {name: 小綠, age: 2} #對象也可以用{}表示